---

- name: install ntp packages
  apt:
    name: '{{ item }}'
    state: 'present'
    update_cache: True
    cache_valid_time: 86400
  with_items:
    - 'ntp'
    - 'ntpstat'
    - 'tzdata'

- name: run and enable ntp
  service:
    name: 'ntp'
    state: 'started'
    enabled: True
