language: python
install: true
sudo: false
jobs:
  include:
    - stage: test
      script: bash travis-staging.sh
    - stage: deploy
      script: bash travis-production.sh
before_install:
    - openssl aes-256-cbc -K $encrypted_2c430460807a_key -iv $encrypted_2c430460807a_iv 
      -in srcluster.enc -out /tmp/travis_key -d
    - eval "$(ssh-agent -s)"
    - chmod 600 /tmp/travis_key
    - ssh-add /tmp/travis_key

